apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fas54-prometheusrules
spec:
  groups:
  - name: fas54.rules
    rules:
    - alert: Fas54HighRequestLatency
      expr: increase(fas54_request_latency_bucket[1m]) > 0.5